var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                              o ",
   "                                                                                ",
   "                                                                xx xx           ",
   "                                                   xx     xx   xx   xx          ",
   "                                    o o      xx     x!!!!!x     x!!!x    x      ",
   "                                         x          xxxxxxx     xx!xx   xxx     ",
   "                                 xxxxx                           xxx     x      ",
   "                              x  x   x                 o                       y",
   "                              x  xxxxx         xx              x             xxx",
   "                      xxxxx                            x      xxx           xx x",
   "  xxxx        e       xooox             xxxxx      x       x                x  x",
   "  x          xxxx     x                 xo                        x         x  x",
   "  x @  x     x  x    x e           xxxxxx                        x x   x    xxxx",
   "  xxxxxx     xxxx   xxxxxxxx      xx    xxxxxx   xxxxx     xxx  x   x  xx       ",
   "                                             x!!!x   xx   xx   xxx xxxxx   x    ",
   "                           o    x            xxxxx                              ",
   "                  xxx          xxxxx       o o o o o    x               xx      ",
   "                       xxx   x            o o o o o o                o          ",
   "                         x!!!x             e      e    x     xxxxx         x    ",
   "                         xxxxx          xxxxxxxxxxxxxxxx     x   x              ",
   "                                                             xxxxx    xxxx      ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                                          ",
   "                                      x!!x                                          ",
   "                                      xx!!!!!!!!!!xx                         y      ",
   "                                       xxxxxxxxxx!!x                  E     xxx     ",
   "                                                xx!x                         x      ",
   "                                                 x!x                  x            x",
   "                                                 xvx                             o  ",
   "                                                           E    x                   ",
   "                                                                                   x",
   "                                                           x                     o  ",
   "                                               xx   xx                              ",
   "                                               xxx xxx                             x",
   "                                              xx xox xx  o                       o  ",
   "                                               x  x  x                       o      ",
   "                           E                   x     x                             x",
   " @               e  e                          xx     xx              xxxxx          ",
   "xxxx    xx     xxxxxxx     x    x   xxx        x     x   o          xxxxxxx         ",
   "xxxx          xx     xx         x   x          x     x        xx     xxxxx   xxxx  x",
   "xxxx  o      xx   o   xx        x o x         xx     xx      xxx     xxxxx!!!x  x   ",
   "xxxx        xx   ooo   x        x   x          x     x                   x!!!x  x   ",
   "xxxx         x  ooooo  x        x   x     xx   x     x    x              xxxxx o   x",
   "xxxx  o      x         x!!!!!!!!x o xxx!!!!!!!!xx    x!!!!!!!!!!          x    =    ",
   "xxxx        xxx   xx   xx!!!!!!xx     xxxxxxxxxx     xxxxxxxxxxxx    x              ",
   "xxxx         xx         xxxxxxxx                                         x         x",
   "xxxx  o      xx                   o                                      o     x    ",
   "xxxx        xxx     x                                                   o o         ",
   "xxxx  x      xx                                                        xxxxx        ",
   "xxxx!!!!!!!!!xx       x           x                                                 ",
   "xxxxxxxxxxxxxxx           xxxxxx!!!!!xxxx      xx     xx     xx    xx               ",
   "                               xxxxxxx                                              ",
   "                                                                                    "],
  ["                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "     xxxx  xxxx  x   x  x  x  xxxx  x  x  x      ",
   "     x  x  x  x  xx  x  x  x  x     x  x  x      ",
   "     xxxx  x  x  x x x  x  x  xxxx  x  x  x      ",
   "     x  x  x  x  x  xx  x  x     x               ",
   "     xxxx  xxxx  x   x  xxxx  xxxx  x  x  x      ",
   "                                                 ",
   "                                                 ",
   "                                                 ",                                          
   "     o o o o o o o o o o o o o o o o o o o o     ",
   " @  o o o o o o o o o o o o o o o o o o o o o   y",                                                                     
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], 
                                                                                                              
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
